use_frameworks!

platform :ios, '9.0'

target 'lelePodsKit_Example' do
  pod 'lelePodsKit', :path => '../'
#  pod 'MJRefresh', '~> 3.4.1'
pod 'SnapKit', '4.0.1'
  target 'lelePodsKit_Tests' do
    inherit! :search_paths

    
  end
end
